### ISSUE TITLE
[Feat] Consider data-model

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzk_py#1]
## Describe the new feature<br/>
Set up data-model for chzzk service

## TODO<br/>
- [x] Set-up DataModel
    - [x] Base Model (ChzzkModel)
    - [x] Live Detail (`/service/v2/channels/{channel_id}/live-detail`)
    - [x] Live Status (`/polling/v2/channels/{channel_id}/live-status`)
    - [x] Chat Access Token (`/nng_main/v1/chats/access-token?channelId={channel_id}&chatType=STREAMING`)
    - [x] User Status (`/nng_main/v1/user/getUserStatus`)

## Addition Context<br/>
1. Developed for chatting with websockets, python
2. Based on `aiohttp`, `pydantic` and `async-client-decorator`
