### ISSUE TITLE
[Feat] Add more exception

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzk_py#18]
## Describe the bug<br/>
Add more exception process.
* chat connection failed
* response error code
* channel not found

## Original Issue<br/>
- related at #17 

## TODO<br/>
- [x] Add base exception
- [x] Add `ChatConnectionFailed` exception, when live_status method result is None.
- [x] Add `NotFound` exception.
- [x] Add `HTTPException` exception.
