### ISSUE TITLE
[Feat] Consider HTTP Client

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzk_py#2]
## Describe the new feature<br/>
Set up `Client` and `HTTP Client` to use chzzk live streaming service.

## TODO<br/>
- [x] Consider HTTP Client (base_url = `https://api.chzzk.naver.com/`)
    - [x] `live_status` method
    - [x] `live_detail` method
- [x] Consider HTTP Client (base_url = `https://comm-api.game.naver.com`)
    - [x] `get_user_status` method
    - [x] `_chat_access_token(Alias)` method
- [x] Consider Client to manage two HTTP Client.

## Addition Context<br/>
- Related issue #1
