### ISSUE TITLE
[Feat] More advanced feature Mission Donation

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzk_py#21]
## Describe the new feature<br/>
Add Mission Donation Event

## TODO<br/>
- [x] Add `on_mission_pending` event
- [x] Add `on_mission_rejected/approved` event
- [x] Add `on_mission_complete` event
- [x] Divide data class struction `donation.py` from `message.py` 
- [x] Fix wrong literial type (MissionDontationExtra)

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added new events for mission donations, created MissionDonation data class, and fixed the literal type in MissionDonationExtra.

I also created pull request: https://github.com/gunyu1019/chzzk_py/pull/22


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by gunyu1019** [comment]
This is an example for mission donation data.
```jsx
{
    "missionDonationType": "ALONE", // ?
    "durationTime": "(number) second",
    "missionDonationId": "MISSION DONATION ID",
    "donationId": null,
    "totalPayAmount": 0,
    "missionText": "MISSION TEXT",
    "donationType": "MISSION",
    "isAnonymous": false,
    "missionEndTime": "MISSION END TIME",
    "verifiedMark": false,
    "payType": "CURRENCY",
    "payAmount": 0,
    "participationCount": 0,
    "userIdHash": "USER ID HASH",
    "success": false,
    "nickname": "NICKNAME",
    "missionCreatedTime": "CREATED TIME", 
    "status": "PENDING | REJECTED | APPROVED"
}
```
