### ISSUE TITLE
[Feat] Chat with chzzk-live

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzk_py#3]
## Describe the new feature<br/>
Consider chatting client

## TODO<br/>
- [x] Class `ChatClient`
    - [x] `connect` method (websocket)
    - [x] event listener
    - [x] event listener with `wait_for` method
    - [x] `send_chat` method
    - [x] `history` method
- [x] Class `Gateway(ChzzkWebsocket)`
    - [x] `poll_event` method to receive data
    - [x] `send_ping` method
    - [x] `send_pong` method
    - [x] Websocket Keep-Alive
    - [x] `send_chat` method
    - [x] `recent_chat` method (IDK.. I think message history)
- [x] Class `State(Alias)?` to parse data from websocket.
    - [x] `hook` from Gateway and `dispatch` to Client
    - [x] `parse_chat` method
    - [x] `parse_donation` method
    - [x] `parse_resent_chat` method
    - [x] `parse_notice` method
    - [x] `parse_blind` method
    - [ ] `parse_penalty` method
    - [ ] `parse_event` method

## Addition Context<br/>
- Related issue #2
